import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { UserProvider } from '@/context/UserContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={inter.className}>
                {/* <Header />
                <div className="pt-[67.2px] pb-[24px] bg-[#f8f8f8]">
                    {children}
                </div>
                <Footer /> */}

                <UserProvider>
                    <Header />
                    <div className="pt-[67.2px] pb-[24px] bg-[#f8f8f8]">
                        {children}
                    </div>
                    <Footer />
                </UserProvider>
            </body>
        </html>
    );
}
